### ISSUE TITLE
EPIC generated schema docs and maps improvements

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#120]
# User Story:

For functionality and usability, we need to address a number of glitches in the documentation (web pages) currently generated for XML and JSON schemas produced from metaschema sources. These include both the model documentation and the model maps.

## Goals:

This is an EPIC representing a number of work items relating to the web side and generated schema documentation.

https://github.com/usnistgov/metaschema/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation

This order might make sense
- [ ] #71
- [ ] #113
- [ ] #94 (refactoring main page navigation in general)
- [ ] #104
- [ ] #105 #91 #92

Also visit
- [ ] empty elements (cf usnistgov/OSCAL#829)
- [ ] scrolling issues with menu? usnistgov/OSCAL#787

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by wendellpiez** [comment]
Pushed draft PR here: #127

So far we have corrections or improvements addressing usnistgov/OSCAL#847 usnistgov/OSCAL#848 and usnistgov/OSCAL#670.

Next comes a more substantive overhaul of nav/layout for main docs pages, to improve usability and transparency.

**Comment by wendellpiez** [comment]
**Progress report March 25**

Several small but tricky issues (mainly with model maps) have been addressed. Remaining issues have to do with linking and navigation. The new pages will each index to names of structures in the format - that is, users will be able to look up the names of elements (in XML) and objects (in JSON) without having to know their metaschema object types in advance. Work on this is underway.

**Comment by wendellpiez** [comment]
#91 and #105 are done.

#94 and #104 could be pushed to #128, which is a dependency for them.

This leaves usnistgov/OSCAL#787 and #92, both possibly lower priority.

**Comment by aj-stein-nist** [comment]
This epic combines some bug/feature enhancements for the XSLT implementation and doc generation pipeline, and other issues are about improvements to Metaschema. Split out the epics accordingly to properly prioritize epics and their issues.

**Comment by david-waltermire-nist** [comment]
We should discuss the remaining work here and #48 with @aj-stein-nist. It would be good to close this and create a new clean EPIC to outline documentation generation work needed going forward.
