### ISSUE TITLE
Enhance Metaschema Unit Testing Framework

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/metaschema#186]
# User Story:

As a Metaschema-tooling developer, to have more confidence that I am properly implementing my own tools that parse Metaschema, I would like to have a more organized collection of unit and integration tests, where I can use this repository's test runner or reuse the test data inputs and outputs with my own alternative test runner for conformance testing.

## Goals:

Unit Tests should be reorganized with an organization scheme and implementation that identifies how the test implements one or more of the following goals:

- [ ] The Metaschema itself is syntactically valid
- [ ] The XML Schema for valid Metaschema is well-formed
- [ ] The JSON Schema for valid Metaschema is well-formed
- [ ] The Metaschema emits an expected XML Schema structure for given Metaschema
- [ ] The Metaschema emits an expected JSON Schema structure for given Metaschema

Tests should be reorganized with an organization scheme and implementation that identifies how the test implements one or more of the following goals:

- [ ] How the JSON Schema validation behave in common language runtimes (aka conformance test)
- [ ] How the XML Schema validation behave in common language runtimes (aka conformance test)

## Dependencies:

Iterating and prototyping a first attempt or an interrim solution as part of ongoing work in usnistgov/metaschema#183 and usnistgov/metaschema#184.

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist, before I forget: an epic tracker given our discussion today on enhancing the unit tests, and maybe later integration tests. Look forward to syncing up again on Friday to discuss this further.

**Comment by aj-stein-nist** [comment]
Preliminary work has begun on some work in this epic and new issues will be drawn out. Will move this to assigned to developer.

**Comment by wendellpiez** [comment]
I am working on this Issue here, with provisional XSpec underway: https://github.com/wendellpiez/metaschema/tree/feature-metaschema-relocation-plus-enhancementsA
