### ISSUE TITLE
Improve Intergration and Unit Tests for Metaschema Composition Pipeline

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/metaschema#201]
# User Story:

As a NIST OSCAL developer, to have more confidence in the Metaschema composition pipeline for NIST's primary XSLT-based implementation as-is and when I develop for new features and fixing bugs, I would like to see unit tests to validate individual pipeline components and end-to-end integration tests for the complete pipeline of transformations from input to desired composition output.

## Goals:

There are existing integration tests for the Metaschema composition to test end-to-end functionality and new unit tests to validate the phase that prunes unused definitions in #199. We would like to revive the existing integration tests and add MVP unit tests for other phases of the composition pipeline for MVP test coverage and confidence in the pipeline during changes.

## Dependencies:

- [ ] Completion of #199 and resolution of #198.

## Acceptance Criteria

- [ ] Fix broken XSpec integration-level (end-to-end ) tests for Metaschema composition for minimally required test coverage
- [ ] Add relevant XSpec tests for minimally required test coverage
- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by aj-stein-nist** [comment]
We know next steps for the immediate bug fix and test cleanup work, the long-term composition testing details on what is enough and good enough in terms of goals we need to discuss we can pick up in another triage session.
