### ISSUE TITLE
Add Documentation for Local Refinements for Metaschema Syntax

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/metaschema#237]
# User Story:

As a NIST OSCAL developer, in order to better understand how to locally define `flag`s, `allowed-value`s, and `json-key`s, I would like more documentation on how to use them in Metaschema definitions.

## Goals:

- [x] Replace TBDs with documentation for `flags` (addressed in PR #329)
- [ ] Replace TBDs with documentation for `allowed-value`s (addressed in #411 and by PR #413)
- [ ] Replace TBDs with documentation for `json-key`s (addressed in #316)

## Dependencies:

{Describe any previous issues or related work that must be completed to start or complete this issue.}

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by aj-stein-nist** [comment]
Per discussion with team reorganization, I will move this Metaschema issue off the NIST OSCAL workboard.
