### ISSUE TITLE
Additional constraints epic

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/metaschema#485]
# User Story:

As a Metaschema developer, in order to understand how explain, design, and implement usage of Metaschema-based models, I need an updates [to the specification on the Metaschema website re enumerated values](https://pages.nist.gov/metaschema/specification/syntax/constraints/) to document how to use all constraint types, not just the most common allowed-values enumeration constraint type documented in usnistgov/metaschema#411 work.

This will document those constraints currently identified [in the Metaschema XML Schema that defines the syntax of a module](https://github.com/usnistgov/metaschema/blob/211dcfc4697556409067573cd0c1cf7483572916/schema/xml/metaschema.xsd).

## Goals:

Document all the constraint types in metaschema, including:

- [x] `allowed-values` (completed in usnistgov/metaschema#411)
- [x] #546
- [x] #489
- [x] #490
- [x] #491
- [x] #492
- [x] #496

(**NOTE:** I added a check to confirm the work is almost complete or in the process of final review, unchecked items are free for other members of the maintainer team to pick up.)

## Dependencies:

N/A

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by aj-stein-nist** [comment]
I checked off ones that are far enough in review they are "done" and I might want some help starting others. @Arminta-Jenkins-NIST, when you are back next week, do you think we could work together to document `is-unique` and `match` for #491 and #492 respectively? I would like some fresh eyes to make sure what I wrote before makes sense: these should be very straightforward given the explanation in the others.

**Comment by aj-stein-nist** [comment]
Alongside #545, I am adding #546 to this epic as it fell through the cracks. I can handle this quickly later today or early tomorrow morning.
