### ISSUE TITLE
Constraint Tutorials

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/metaschema#526]
# User Story:

As a Metaschema tooling developer, in order to better understand how I can maximally leverage Metapath-based constraints for precise information model structure and data format validation, I would like more tutorials that incrementally build off the [initital tutorial](https://pages.nist.gov/metaschema/tutorials/1-getting-started/) with a scaffolded example. That way I can understand [the specification]() modeling and Metaschema processor operations with complementary detail from these progressive tutorials.

## Goals:

{A clear and concise description of what you want to happen. This should be outcome focused. Include concise description of any alternative solutions or features you've considered. Feel free to include screenshots or examples about the feature request here.}

## Dependencies:

{Describe any previous issues or related work that must be completed to start or complete this issue.}

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}
