### ISSUE TITLE
Document required or recommend schema serializations

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/metaschema#557]
# User Story:

As a Metaschema developer, in order to make properly equivalent schemas for subset of supported schema serializations (i.e. at this time JSON Schema, XML Schema) so that I can make conformant tools to that properly generate a conformant serialized schema from a Metaschema module to conform with the specification.

## Goals:

- [ ] Clearly document expectations regarding generation for any developer
- [ ] Provide a supporting test suite with example models, valid output JSON/XML schemas, output JSON/XML schemas for testing existing and emerging implementations
- [ ] Decrease bugs in different between the NIST Java, NIST XSLT, and community implementations of Metaschema processors

## Dependencies:

N/A

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that adds the documentation.
- [ ] - [ ] A Pull Request (PR) is submitted that adds the unit tests.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}
